import type { LocationDef } from '@/core/types';

/**
 * Locations own their loot tables. Adding a location is a data change only —
 * no gameplay code references a specific location id.
 */
export const LOCATIONS: LocationDef[] = [
  {
    id: 'loc_old_park',
    name: 'Old Park',
    subtitle: 'Municipal green, est. 1904',
    description:
      'Mown grass over a century of picnics, parades and dropped change. Shallow, friendly ground — a good place to learn what your detector is telling you. Most of what comes up here is exactly what it looks like. Not quite everything.',
    bounds: { w: 1400, h: 1400 },
    targetCount: [7, 10],
    depthBias: 0.85,
    hardness: 0.3,
    ambience: 'park',
    ground: {
      base: '#2b3b26',
      mid: '#3d5230',
      light: '#55703d',
      detail: '#6d8a47',
      haze: '#1a2419',
      sky: '#7e9a6b',
      scatter: 'grass',
    },
    table: [
      { targetId: 'tgt_bottle_cap', weight: 16 },
      { targetId: 'tgt_pull_tab', weight: 16 },
      { targetId: 'tgt_foil', weight: 10 },
      { targetId: 'tgt_washer', weight: 9 },
      { targetId: 'tgt_screw', weight: 9 },
      { targetId: 'tgt_wire', weight: 7 },
      { targetId: 'tgt_nail', weight: 8 },
      { targetId: 'tgt_scrap', weight: 7 },
      { targetId: 'tgt_modern_coin', weight: 11 },
      { targetId: 'tgt_old_coin', weight: 5 },
      { targetId: 'tgt_vintage_button', weight: 4 },
      { targetId: 'tgt_old_key', weight: 3 },
      { targetId: 'tgt_thimble', weight: 2.5 },
      { targetId: 'tgt_pocket_knife', weight: 2 },
      { targetId: 'tgt_horseshoe', weight: 1.5 },
      { targetId: 'tgt_silver_coin', weight: 1.2 },
      { targetId: 'tgt_signet_ring', weight: 0.6 },
      { targetId: 'tgt_brakeman_badge', weight: 0.7 },
      { targetId: 'tgt_survey_tag', weight: 0.7 },
      { targetId: 'tgt_shard_a', weight: 2.2 },
      { targetId: 'tgt_shard_b', weight: 2.2 },
      { targetId: 'tgt_shard_c', weight: 1.6 },
    ],
  },
  {
    id: 'loc_old_railway',
    name: 'Old Railway',
    subtitle: 'Abandoned spur, closed 1931',
    description:
      'Ballast, rotted sleepers and the iron confetti of fifty working years. The junk is louder here, but so is everything else — including things that were never railway property to begin with.',
    bounds: { w: 1500, h: 1500 },
    targetCount: [8, 11],
    depthBias: 1.05,
    hardness: 0.55,
    ambience: 'railway',
    ground: {
      base: '#2e2a24',
      mid: '#443b30',
      light: '#5b4e3d',
      detail: '#6f6150',
      haze: '#1b1814',
      sky: '#8a7d69',
      scatter: 'gravel',
    },
    table: [
      { targetId: 'tgt_nail', weight: 18 },
      { targetId: 'tgt_scrap', weight: 14 },
      { targetId: 'tgt_tin_fragment', weight: 11 },
      { targetId: 'tgt_bottle_cap', weight: 9 },
      { targetId: 'tgt_washer', weight: 8 },
      { targetId: 'tgt_screw', weight: 8 },
      { targetId: 'tgt_wire', weight: 6 },
      { targetId: 'tgt_old_coin', weight: 6 },
      { targetId: 'tgt_buckle', weight: 5 },
      { targetId: 'tgt_old_spanner', weight: 5 },
      { targetId: 'tgt_military_button', weight: 4 },
      { targetId: 'tgt_old_key', weight: 3.5 },
      { targetId: 'tgt_horseshoe', weight: 3 },
      { targetId: 'tgt_pocket_knife', weight: 2.5 },
      { targetId: 'tgt_silver_coin', weight: 2.2 },
      { targetId: 'tgt_medal', weight: 1.4 },
      { targetId: 'tgt_locket', weight: 1 },
      { targetId: 'tgt_brakeman_badge', weight: 1.6 },
      { targetId: 'tgt_survey_tag', weight: 1.6 },
      { targetId: 'tgt_bronze_token', weight: 0.7 },
      { targetId: 'tgt_unknown_artifact', weight: 0.4 },
      { targetId: 'tgt_shard_a', weight: 1.8 },
      { targetId: 'tgt_shard_b', weight: 1.8 },
      { targetId: 'tgt_shard_c', weight: 2.4 },
    ],
  },
  {
    id: 'loc_abandoned_mine',
    name: 'Abandoned Mine',
    subtitle: 'Spoil heaps, north-west spur',
    description:
      'Loose spoil above a working that closed without a recorded reason. Everything here is deeper, harder and stranger than it has any right to be.',
    bounds: { w: 1500, h: 1500 },
    targetCount: [7, 10],
    depthBias: 1.35,
    hardness: 0.8,
    ambience: 'mine',
    lockedBy: 'chain_survey',
    lockedHint: 'Somewhere out there. You have no reason to go looking yet.',
    ground: {
      base: '#241f22',
      mid: '#38302f',
      light: '#4c413c',
      detail: '#5e5049',
      haze: '#13100f',
      sky: '#6b5b52',
      scatter: 'rubble',
    },
    table: [
      { targetId: 'tgt_nail', weight: 14 },
      { targetId: 'tgt_scrap', weight: 14 },
      { targetId: 'tgt_tin_fragment', weight: 9 },
      { targetId: 'tgt_screw', weight: 7 },
      { targetId: 'tgt_wire', weight: 6 },
      { targetId: 'tgt_old_spanner', weight: 6 },
      { targetId: 'tgt_buckle', weight: 5 },
      { targetId: 'tgt_old_key', weight: 4 },
      { targetId: 'tgt_military_button', weight: 4 },
      { targetId: 'tgt_pocket_knife', weight: 3 },
      { targetId: 'tgt_silver_coin', weight: 3 },
      { targetId: 'tgt_medal', weight: 2.2 },
      { targetId: 'tgt_signet_ring', weight: 1.6 },
      { targetId: 'tgt_locket', weight: 1.6 },
      { targetId: 'tgt_bronze_token', weight: 2.4 },
      { targetId: 'tgt_stone_fragment', weight: 2.2 },
      { targetId: 'tgt_mechanism_part', weight: 2 },
      { targetId: 'tgt_unknown_artifact', weight: 1.4 },
    ],
  },
  {
    id: 'loc_sealed_chamber',
    name: 'The Sealed Chamber',
    subtitle: 'Beneath the north-west spur',
    description:
      'A cut passage behind a collapsed adit, squared by hands that had no business being this deep this early. At the end of it, something is still holding on to what it was given.',
    bounds: { w: 900, h: 900 },
    targetCount: [0, 0],
    depthBias: 1,
    hardness: 1,
    ambience: 'mine',
    lockedBy: 'chain_sun',
    lockedHint: 'Deeper than anything you currently have a name for.',
    adventureId: 'adv_sealed_chamber',
    ground: {
      base: '#1a1618',
      mid: '#2a2326',
      light: '#3a2f30',
      detail: '#4a3c39',
      haze: '#0b0909',
      sky: '#4a3b38',
      scatter: 'rubble',
    },
    table: [],
  },
  {
    id: 'loc_courtyard',
    name: 'The Overgrown Courtyard',
    subtitle: 'Walled ground, no record of use',
    description:
      'Four low walls, mostly fallen, enclosing a square of ground that ivy took over long before anyone here was born. Whoever built it faced the entrance toward the old mine workings — which were not old, when this was built.',
    bounds: { w: 700, h: 700 },
    targetCount: [0, 0],
    depthBias: 1,
    hardness: 1,
    ambience: 'ruins',
    lockedBy: 'chain_tablet_bound',
    lockedHint: 'The tablet, whole, pointed toward somewhere walled and overgrown.',
    adventureId: 'adv_courtyard',
    ground: {
      base: '#232a1d',
      mid: '#333e26',
      light: '#465532',
      detail: '#5a6a3f',
      haze: '#141a10',
      sky: '#5c6b45',
      scatter: 'rubble',
    },
    table: [],
  },
];

const LOCATION_INDEX = new Map(LOCATIONS.map((l) => [l.id, l]));

export function getLocation(id: string): LocationDef | undefined {
  return LOCATION_INDEX.get(id);
}
