import type { TargetDef } from '@/core/types';

/**
 * Every findable object in the game. This is pure data: gameplay systems only
 * ever see TargetDef fields, never specific ids.
 *
 * Distribution note: the junk list is deliberately long and cheap to roll.
 * Finding rubbish is the point — it is what makes a silver coin land.
 */
export const TARGETS: TargetDef[] = [
  // ── First-run teaching target ──────────────────────────────────────────────
  {
    id: 'tgt_tut_penny',
    name: 'Worn Penny',
    category: 'coin',
    material: 'nonFerrous',
    materialName: 'Bronze',
    rarity: 'common',
    era: 'Mid 1900s',
    depth: [7, 9],
    size: 0.5,
    value: 1,
    significance: 'none',
    // Deliberately indestructible: nobody's first dig should end in ruin.
    fragility: 0,
    excavationDifficulty: 0.12,
    description: 'An everyday coin, dropped and forgotten. Almost every field has a few.',
    discoveryText: 'Somebody lost this on a walk, decades ago, and never thought about it again.',
    silhouette: 'coin',
    tutorial: true,
  },

  // ── Common: junk ───────────────────────────────────────────────────────────
  {
    id: 'tgt_bottle_cap',
    name: 'Bottle Cap',
    category: 'junk',
    material: 'ferrous',
    materialName: 'Crimped steel',
    rarity: 'common',
    era: 'Modern',
    depth: [3, 12],
    size: 0.35,
    value: 0,
    significance: 'none',
    fragility: 0,
    excavationDifficulty: 0.1,
    description: 'Rusted, crimped, and utterly without mystery.',
    discoveryText: 'A bottle cap. The ground gives these up freely.',
    silhouette: 'bottlecap',
  },
  {
    id: 'tgt_pull_tab',
    name: 'Pull Tab',
    category: 'junk',
    material: 'nonFerrous',
    materialName: 'Aluminium',
    rarity: 'common',
    era: 'Modern',
    depth: [2, 10],
    size: 0.28,
    value: 0,
    significance: 'none',
    fragility: 0,
    excavationDifficulty: 0.08,
    description: 'Reads almost exactly like a small gold ring on most detectors. Cruel.',
    discoveryText: 'A pull tab. It had the decency to sound valuable.',
    silhouette: 'pulltab',
  },
  {
    id: 'tgt_nail',
    name: 'Square Nail',
    category: 'junk',
    material: 'ferrous',
    materialName: 'Wrought iron',
    rarity: 'common',
    era: 'Late 1800s',
    depth: [4, 16],
    size: 0.4,
    value: 0,
    significance: 'minor',
    fragility: 0,
    excavationDifficulty: 0.2,
    description: 'Hand-cut and square-shanked. Worthless alone, but nails mean buildings.',
    discoveryText: 'An old square nail. Something stood here once.',
    silhouette: 'nail',
  },
  {
    id: 'tgt_scrap',
    name: 'Scrap Metal',
    category: 'junk',
    material: 'ferrous',
    materialName: 'Corroded steel',
    rarity: 'common',
    era: 'Unknown',
    depth: [4, 18],
    size: 0.75,
    value: 0,
    significance: 'none',
    fragility: 0,
    excavationDifficulty: 0.3,
    description: 'A shapeless lump of rust that screamed like a treasure chest.',
    discoveryText: 'Scrap. Big signal, big hole, big nothing.',
    silhouette: 'scrap',
  },
  {
    id: 'tgt_modern_coin',
    name: 'Modern Coin',
    category: 'coin',
    material: 'nonFerrous',
    materialName: 'Nickel-clad',
    rarity: 'common',
    era: 'Modern',
    depth: [2, 9],
    size: 0.45,
    value: 1,
    significance: 'none',
    fragility: 0.05,
    excavationDifficulty: 0.1,
    description: 'Still legal tender. Barely.',
    discoveryText: 'Pocket change, returned to you by the ground.',
    silhouette: 'coin',
  },
  {
    id: 'tgt_washer',
    name: 'Washer',
    category: 'junk',
    material: 'ferrous',
    materialName: 'Galvanised steel',
    rarity: 'common',
    era: 'Modern',
    depth: [3, 13],
    size: 0.33,
    value: 0,
    significance: 'none',
    fragility: 0,
    excavationDifficulty: 0.12,
    description: 'A perfect circle of disappointment.',
    discoveryText: 'A washer. For one lovely second it sounded like a coin.',
    silhouette: 'washer',
  },
  {
    id: 'tgt_screw',
    name: 'Rusted Screw',
    category: 'junk',
    material: 'ferrous',
    materialName: 'Steel',
    rarity: 'common',
    era: 'Modern',
    depth: [3, 14],
    size: 0.3,
    value: 0,
    significance: 'none',
    fragility: 0,
    excavationDifficulty: 0.14,
    description: 'Threaded, seized, and thoroughly uninteresting.',
    discoveryText: 'A screw. Onwards.',
    silhouette: 'screw',
  },
  {
    id: 'tgt_wire',
    name: 'Twist of Wire',
    category: 'junk',
    material: 'nonFerrous',
    materialName: 'Copper',
    rarity: 'common',
    era: 'Modern',
    depth: [3, 15],
    size: 0.4,
    value: 0,
    significance: 'none',
    fragility: 0,
    excavationDifficulty: 0.12,
    description: 'Fence wire, probably. Copper sings nicely, which makes this worse.',
    discoveryText: 'Wire. A beautiful tone for a piece of rubbish.',
    silhouette: 'wire',
  },
  {
    id: 'tgt_foil',
    name: 'Crumpled Foil',
    category: 'junk',
    material: 'nonFerrous',
    materialName: 'Foil',
    rarity: 'common',
    era: 'Modern',
    depth: [1, 7],
    size: 0.25,
    value: 0,
    significance: 'none',
    fragility: 0,
    excavationDifficulty: 0.05,
    description: 'Every detector lies about foil. Every single one.',
    discoveryText: 'Foil. The great impostor.',
    silhouette: 'scrap',
  },
  {
    id: 'tgt_tin_fragment',
    name: 'Tin Can Fragment',
    category: 'junk',
    material: 'ferrous',
    materialName: 'Tinplate',
    rarity: 'common',
    era: 'Early 1900s',
    depth: [5, 17],
    size: 0.6,
    value: 0,
    significance: 'none',
    fragility: 0,
    excavationDifficulty: 0.25,
    description: 'A shard of a can that fed somebody a very long time ago.',
    discoveryText: 'Part of an old can, torn and blackened.',
    silhouette: 'tin',
  },

  // ── Uncommon ───────────────────────────────────────────────────────────────
  {
    id: 'tgt_old_key',
    name: 'Old Key',
    category: 'personal',
    material: 'ferrous',
    materialName: 'Iron',
    rarity: 'uncommon',
    era: 'Early 1900s',
    depth: [6, 20],
    size: 0.5,
    value: 6,
    significance: 'minor',
    fragility: 0.2,
    excavationDifficulty: 0.35,
    description: 'A skeleton key, its ward worn thin. Whatever it opened is long gone.',
    discoveryText: 'A key. Somewhere there was a door that mattered.',
    silhouette: 'key',
  },
  {
    id: 'tgt_pocket_knife',
    name: 'Pocket Knife',
    category: 'tool',
    material: 'ferrous',
    materialName: 'Steel and bone',
    rarity: 'uncommon',
    era: '1920s–1940s',
    depth: [7, 22],
    size: 0.55,
    value: 9,
    significance: 'minor',
    fragility: 0.35,
    excavationDifficulty: 0.4,
    description: 'Folded shut for a century. The bone scales have gone the colour of tea.',
    discoveryText: 'A pocket knife, still folded, still waiting.',
    silhouette: 'knife',
  },
  {
    id: 'tgt_vintage_button',
    name: 'Vintage Button',
    category: 'personal',
    material: 'nonFerrous',
    materialName: 'Brass',
    rarity: 'uncommon',
    era: 'Late 1800s',
    depth: [5, 18],
    size: 0.3,
    value: 4,
    significance: 'minor',
    fragility: 0.3,
    excavationDifficulty: 0.3,
    description: 'A brass coat button with a faint floral stamp.',
    discoveryText: 'A button from a coat nobody has worn in a hundred years.',
    silhouette: 'button',
  },
  {
    id: 'tgt_old_coin',
    name: 'Wheat Cent',
    category: 'coin',
    material: 'nonFerrous',
    materialName: 'Copper',
    rarity: 'uncommon',
    era: '1910s–1950s',
    depth: [6, 20],
    size: 0.45,
    value: 7,
    significance: 'minor',
    fragility: 0.15,
    excavationDifficulty: 0.3,
    description: 'Two ears of wheat on the reverse, both nearly smoothed away.',
    discoveryText: 'An old cent, green with age. The date is just barely there.',
    silhouette: 'coin',
  },
  {
    id: 'tgt_buckle',
    name: 'Harness Buckle',
    category: 'tool',
    material: 'nonFerrous',
    materialName: 'Brass',
    rarity: 'uncommon',
    era: 'Late 1800s',
    depth: [8, 24],
    size: 0.6,
    value: 8,
    significance: 'minor',
    fragility: 0.2,
    excavationDifficulty: 0.45,
    description: 'Horse tack. Heavy, practical, and older than the road beside it.',
    discoveryText: 'A buckle from a harness. There were horses here.',
    silhouette: 'buckle',
  },
  {
    id: 'tgt_thimble',
    name: 'Sewing Thimble',
    category: 'personal',
    material: 'silver',
    materialName: 'Plated silver',
    rarity: 'uncommon',
    era: '1880s–1910s',
    depth: [4, 16],
    size: 0.28,
    value: 12,
    significance: 'minor',
    fragility: 0.45,
    excavationDifficulty: 0.25,
    description: 'Dented from decades of use before it was ever lost.',
    discoveryText: 'A thimble, dimpled and bright where the dirt wiped away.',
    silhouette: 'thimble',
  },
  {
    id: 'tgt_military_button',
    name: 'Military Button',
    category: 'military',
    material: 'nonFerrous',
    materialName: 'Gilt brass',
    rarity: 'uncommon',
    era: 'Early 1900s',
    depth: [6, 21],
    size: 0.32,
    value: 16,
    significance: 'notable',
    fragility: 0.3,
    excavationDifficulty: 0.35,
    description: 'A regimental button. The device is crisp enough to identify, one day.',
    discoveryText: 'A uniform button. Somebody marched through here.',
    silhouette: 'button',
  },
  {
    id: 'tgt_old_spanner',
    name: "Railwayman's Spanner",
    category: 'tool',
    material: 'ferrous',
    materialName: 'Forged steel',
    rarity: 'uncommon',
    era: '1890s–1930s',
    depth: [9, 26],
    size: 0.85,
    value: 11,
    significance: 'minor',
    fragility: 0.1,
    excavationDifficulty: 0.55,
    description: 'A heavy track spanner, jaws still square. Built to outlive its owner.',
    discoveryText: 'A track spanner, thick with rust but unmistakable.',
    silhouette: 'spanner',
    locations: ['loc_old_railway', 'loc_abandoned_mine'],
  },
  {
    id: 'tgt_horseshoe',
    name: 'Horseshoe',
    category: 'tool',
    material: 'ferrous',
    materialName: 'Iron',
    rarity: 'uncommon',
    era: 'Late 1800s',
    depth: [8, 25],
    size: 0.9,
    value: 5,
    significance: 'minor',
    fragility: 0.05,
    excavationDifficulty: 0.5,
    description: 'Worn unevenly on one side. That horse favoured a leg.',
    discoveryText: 'A horseshoe, nails still in two of the holes.',
    silhouette: 'horseshoe',
  },

  // ── The Bound Tablet: fragments found in the ordinary places ──────────────
  // Individually these are minor uncommon finds — a broken shard is not
  // remarkable on its own. What makes them matter is that there are three of
  // them, they carry the same carved pattern, and they fit together.
  {
    id: 'tgt_shard_a',
    name: 'Carved Shard',
    category: 'relic',
    material: 'stone',
    materialName: 'Fired clay',
    rarity: 'uncommon',
    era: 'Unknown',
    depth: [6, 20],
    size: 0.3,
    value: 8,
    significance: 'minor',
    fragility: 0.4,
    excavationDifficulty: 0.35,
    unidentifiedName: 'Unglazed Clay Fragment',
    description:
      'One corner of a small fired-clay tablet. The break is too clean for an accident — this was meant to come apart.',
    discoveryText: 'A shard of old clay, carved on one face.',
    examineText:
      'Turning it in the light, the carving resolves into part of a pattern: two loops, woven through each other. The edge where it broke is sharp and regular, not the ragged line of an accident.',
    clueId: 'clue_shard_a',
    silhouette: 'shard_a',
    pieceOf: 'tgt_bound_tablet',
    locations: ['loc_old_park', 'loc_old_railway'],
  },
  {
    id: 'tgt_shard_b',
    name: 'Carved Shard',
    category: 'relic',
    material: 'stone',
    materialName: 'Fired clay',
    rarity: 'uncommon',
    era: 'Unknown',
    depth: [6, 20],
    size: 0.3,
    value: 8,
    significance: 'minor',
    fragility: 0.4,
    excavationDifficulty: 0.35,
    unidentifiedName: 'Unglazed Clay Fragment',
    description:
      'A second clay shard, the same thickness and colour as one you may already have. The carving continues across the broken edge.',
    discoveryText: 'Another shard. Same clay. Same hand.',
    examineText:
      'Held against the light this piece and the last one share an edge — not just the same material, the same object. The woven pattern runs unbroken from one into the other.',
    clueId: 'clue_shard_b',
    silhouette: 'shard_b',
    pieceOf: 'tgt_bound_tablet',
    locations: ['loc_old_park', 'loc_old_railway'],
  },
  {
    id: 'tgt_shard_c',
    name: 'Carved Shard',
    category: 'relic',
    material: 'stone',
    materialName: 'Fired clay',
    rarity: 'uncommon',
    era: 'Unknown',
    depth: [6, 20],
    size: 0.3,
    value: 8,
    significance: 'minor',
    fragility: 0.4,
    excavationDifficulty: 0.35,
    unidentifiedName: 'Unglazed Clay Fragment',
    description:
      'A third shard from the same broken tablet. With this piece, the outline finally closes.',
    discoveryText: 'A third shard. That closes the shape.',
    examineText:
      'Three shards now, and the woven knot completes into a single unbroken loop across all of them. Whatever this was, it is whole again in every way but physically.',
    clueId: 'clue_shard_c',
    silhouette: 'shard_c',
    pieceOf: 'tgt_bound_tablet',
    locations: ['loc_old_park', 'loc_old_railway'],
  },
  {
    id: 'tgt_bound_tablet',
    name: 'The Bound Tablet',
    category: 'artifact',
    material: 'stone',
    materialName: 'Fired clay, reassembled',
    rarity: 'rare',
    era: 'Unknown',
    depth: [0, 0],
    size: 0.65,
    value: 260,
    significance: 'major',
    fragility: 0.55,
    excavationDifficulty: 1,
    description:
      'Three shards, fitted back into one small tablet. Whole, the carving is not decoration — it is a map. The woven knot marks a crossing point, and one incised line runs past the tablet\'s broken edge, off toward ground you have not searched yet.',
    discoveryText: 'Whole again. It was never decoration — it is a map.',
    clueId: 'clue_tablet_assembled',
    silhouette: 'tablet',
    authored: true,
    assemblyOf: ['tgt_shard_a', 'tgt_shard_b', 'tgt_shard_c'],
  },

  // ── The Overgrown Courtyard's reward ────────────────────────────────────────
  {
    id: 'tgt_courtyard_idol',
    name: 'The Woven Idol',
    category: 'artifact',
    material: 'bronze',
    materialName: 'Bronze, green with age',
    rarity: 'rare',
    era: 'Unknown',
    depth: [0, 0],
    size: 0.5,
    value: 300,
    significance: 'major',
    fragility: 0.5,
    excavationDifficulty: 0.5,
    description:
      'A small standing figure, faceless, with the woven knot cut into its chest where a heart would go. Beneath it, cut into the same flagstone it stood on for however long, a bearing — pointing straight down at the ground above the old mine.',
    discoveryText: 'It was standing on its own clue the whole time.',
    clueId: 'clue_courtyard',
    silhouette: 'idol',
    authored: true,
  },

  // ── Rare ───────────────────────────────────────────────────────────────────
  {
    id: 'tgt_silver_coin',
    name: 'Old Silver Coin',
    category: 'coin',
    material: 'silver',
    materialName: 'Silver (.900)',
    rarity: 'rare',
    era: '1890s',
    depth: [10, 28],
    size: 0.42,
    value: 45,
    significance: 'notable',
    fragility: 0.35,
    excavationDifficulty: 0.45,
    description:
      'A milled silver coin. The portrait is worn to a suggestion, but the lettering survives around the rim.',
    discoveryText: 'A worn coin bearing the profile of a long-forgotten ruler.',
    silhouette: 'coin',
  },
  {
    id: 'tgt_medal',
    name: 'Service Medal',
    category: 'military',
    material: 'bronze',
    materialName: 'Bronze',
    rarity: 'rare',
    era: '1910s',
    depth: [10, 26],
    size: 0.5,
    value: 60,
    significance: 'major',
    fragility: 0.5,
    excavationDifficulty: 0.5,
    description:
      'A campaign medal, ribbon long rotted away. A name is stamped along the rim — most of it, anyway.',
    discoveryText: 'A medal. Somebody earned this, and somebody lost it.',
    silhouette: 'medal',
  },
  {
    id: 'tgt_signet_ring',
    name: 'Signet Ring',
    category: 'jewelry',
    material: 'gold',
    materialName: 'Low-carat gold',
    rarity: 'rare',
    era: '1900s',
    depth: [7, 22],
    size: 0.26,
    value: 120,
    significance: 'notable',
    fragility: 0.55,
    excavationDifficulty: 0.35,
    description: 'A flat oval bezel with two initials cut into it, crossed by a hairline crack.',
    discoveryText: 'Gold. Small, heavy, and warm against the dirt.',
    silhouette: 'ring',
  },
  {
    id: 'tgt_locket',
    name: 'Mourning Locket',
    category: 'jewelry',
    material: 'silver',
    materialName: 'Silver and glass',
    rarity: 'rare',
    era: '1870s',
    depth: [8, 24],
    size: 0.34,
    value: 95,
    significance: 'major',
    fragility: 0.75,
    excavationDifficulty: 0.4,
    description:
      'The hinge is seized and the glass is clouded, but there is something behind it. A lock of hair, perhaps.',
    discoveryText: 'A locket, still closed. Whatever is inside has been private for 150 years.',
    silhouette: 'locket',
  },
  {
    id: 'tgt_brakeman_badge',
    name: "Brakeman's Badge",
    category: 'relic',
    material: 'nonFerrous',
    materialName: 'Stamped brass',
    rarity: 'rare',
    era: '1890s',
    depth: [9, 25],
    size: 0.38,
    value: 70,
    significance: 'notable',
    fragility: 0.4,
    excavationDifficulty: 0.45,
    description:
      'A crew badge from a line that never appeared on any public timetable. Below the number, a small three-pointed sun.',
    discoveryText: 'A railway badge — but the line number belongs to no railway on record.',
    clueId: 'clue_badge',
    silhouette: 'badge',
    locations: ['loc_old_railway', 'loc_old_park'],
  },
  {
    id: 'tgt_survey_tag',
    name: "Surveyor's Tag",
    category: 'relic',
    material: 'nonFerrous',
    materialName: 'Lead alloy',
    rarity: 'rare',
    era: '1888',
    depth: [10, 27],
    size: 0.3,
    value: 55,
    significance: 'notable',
    fragility: 0.45,
    excavationDifficulty: 0.5,
    description:
      'A stamped survey tag: a bearing, a depth, and a spur heading north-west into ground that was never developed.',
    discoveryText: 'A survey tag, stamped with a heading and a depth.',
    clueId: 'clue_survey',
    silhouette: 'tag',
    locations: ['loc_old_railway', 'loc_old_park'],
  },

  // ── Very rare ──────────────────────────────────────────────────────────────
  {
    id: 'tgt_bronze_token',
    name: 'Bronze Token',
    category: 'artifact',
    material: 'bronze',
    materialName: 'Bronze, unusual cast',
    rarity: 'veryRare',
    era: 'Unknown',
    depth: [14, 32],
    size: 0.36,
    value: 180,
    significance: 'unknown',
    fragility: 0.6,
    excavationDifficulty: 0.6,
    description:
      'Not currency. Not a medal. The face carries a three-pointed sun and a line of characters that match no alphabet you know.',
    discoveryText: 'The symbol appears to depict a three-pointed sun.',
    clueId: 'clue_token',
    silhouette: 'token',
    locations: ['loc_old_railway', 'loc_abandoned_mine'],
  },
  {
    id: 'tgt_stone_fragment',
    name: 'Inscribed Stone Fragment',
    category: 'artifact',
    material: 'stone',
    materialName: 'Basalt',
    rarity: 'veryRare',
    era: 'Unknown',
    depth: [16, 36],
    size: 0.7,
    value: 210,
    significance: 'unknown',
    fragility: 0.7,
    excavationDifficulty: 0.75,
    description:
      'A broken corner of something much larger. The carving is deliberate, deep, and unweathered — as though it spent its life indoors.',
    discoveryText: 'The same three-pointed sun. Cut into stone this time.',
    clueId: 'clue_fragment',
    silhouette: 'fragment',
    locations: ['loc_abandoned_mine'],
  },
  {
    id: 'tgt_mechanism_part',
    name: 'Mechanism Component',
    category: 'artifact',
    material: 'unknown',
    materialName: 'Unknown alloy',
    rarity: 'veryRare',
    era: 'Unknown',
    depth: [18, 38],
    size: 0.55,
    value: 320,
    significance: 'unknown',
    fragility: 0.8,
    excavationDifficulty: 0.85,
    description:
      'A toothed segment machined to a tolerance that should not exist for its age. It is not rusted. It is not tarnished. It is simply waiting.',
    discoveryText: 'Machined teeth. No corrosion. This should not be down here.',
    clueId: 'clue_mechanism',
    silhouette: 'gear',
    locations: ['loc_abandoned_mine'],
  },
  {
    id: 'tgt_unknown_artifact',
    name: '??? Artifact',
    category: 'artifact',
    material: 'unknown',
    materialName: 'Unknown',
    rarity: 'veryRare',
    depth: [15, 34],
    size: 0.5,
    value: 150,
    significance: 'unknown',
    fragility: 0.75,
    excavationDifficulty: 0.7,
    description: 'Material unknown. Origin unknown. Date unknown. The markings appear deliberate.',
    discoveryText: 'You have no idea what this is.',
    silhouette: 'oddity',
    locations: ['loc_abandoned_mine', 'loc_old_railway'],
  },

  // ── Legendary: authored, adventure-only ────────────────────────────────────
  {
    id: 'tgt_sun_disc',
    name: 'The Three-Pointed Sun',
    category: 'artifact',
    material: 'gold',
    materialName: 'Gold over unknown core',
    rarity: 'legendary',
    era: 'Unknown',
    depth: [0, 0],
    size: 0.8,
    value: 2500,
    significance: 'unknown',
    fragility: 0.9,
    excavationDifficulty: 1,
    description:
      'A disc the width of two hands, held in the jaws of a mechanism built to keep it. Three tapered rays, a rim of worn characters, and a weight that does not match its size.',
    discoveryText: 'It comes free, and behind you the chamber begins to move.',
    silhouette: 'sundisc',
    authored: true,
  },

  // ── The Silent Court: a first-person site (content/sites/silentCourt.ts).
  // These are granted by looking at, picking up or digging up specific spots
  // in that 3D space, never rolled from a table.
  {
    id: 'tgt_court_carving_west',
    name: 'Coiled Serpent, West Wall',
    category: 'relic',
    material: 'stone',
    materialName: 'Weathered limestone',
    rarity: 'uncommon',
    era: 'Unknown',
    depth: [0, 0],
    size: 0.5,
    value: 4,
    significance: 'notable',
    fragility: 0,
    excavationDifficulty: 0,
    description:
      'Cut into the base of the west wall, low enough that you have to crouch: a serpent coiled tight around itself, carved deep enough to have survived open air.',
    discoveryText: 'A coiled serpent, worked into the stone at knee height.',
    clueId: 'clue_court_coil_west',
    silhouette: 'carving',
  },
  {
    id: 'tgt_court_carving_east',
    name: 'Coiled Serpent, East Wall',
    category: 'relic',
    material: 'stone',
    materialName: 'Weathered limestone',
    rarity: 'uncommon',
    era: 'Unknown',
    depth: [0, 0],
    size: 0.5,
    value: 4,
    significance: 'notable',
    fragility: 0,
    excavationDifficulty: 0,
    description:
      'The east wall carries the same figure as the west — same coil, same proportions, cut by the same hand. Two walls, apart from each other, marked to match.',
    discoveryText: 'The same coiled serpent. Same wall height, opposite side of the court.',
    clueId: 'clue_court_coil_east',
    silhouette: 'carving',
  },
  {
    id: 'tgt_court_shard',
    name: 'Glazed Shard',
    category: 'artifact',
    material: 'stone',
    materialName: 'Glazed earthenware',
    rarity: 'uncommon',
    era: 'Unknown',
    depth: [0, 0],
    size: 0.35,
    value: 5,
    significance: 'minor',
    fragility: 0.3,
    excavationDifficulty: 0,
    description: 'A curved piece of glazed pottery, too small to say what it was ever part of.',
    discoveryText: 'Not tablet clay — glazed, and from something rounder.',
    silhouette: 'potteryShard',
    pieceOf: 'tgt_court_vessel',
  },
  {
    id: 'tgt_court_hand',
    name: 'Broken Stone Hand',
    category: 'relic',
    material: 'stone',
    materialName: 'Limestone',
    rarity: 'rare',
    era: 'Unknown',
    depth: [18, 30],
    size: 0.45,
    value: 40,
    significance: 'notable',
    fragility: 0.5,
    excavationDifficulty: 0.4,
    unidentifiedName: 'Weathered Stone Fragment',
    description:
      'A hand, broken at the wrist, fingers curled as though it once held something out. It fits nothing you have seen above ground.',
    discoveryText: 'A stone hand, buried apart from whatever it belonged to.',
    examineText:
      'The break at the wrist is old, but clean — sheared, not shattered. Whatever this reached out from, it stood close by.',
    silhouette: 'handFragment',
  },
  {
    id: 'tgt_court_relic',
    name: 'The Coiled Idol',
    category: 'artifact',
    material: 'bronze',
    materialName: 'Cast bronze',
    rarity: 'legendary',
    era: 'Unknown',
    depth: [0, 0],
    size: 0.5,
    value: 1800,
    significance: 'unknown',
    fragility: 0.6,
    excavationDifficulty: 0,
    description:
      'Two serpents, coiled and facing, set into a socket that only a matching hand could ever have opened. It has been waiting exactly here.',
    discoveryText: 'The hand fit. The pedestal opened. This was underneath the whole time.',
    silhouette: 'serpentIdol',
    authored: true,
  },

  // ── Scenery clues: fixed surface details in the three detecting fields,
  // found by looking rather than sweeping. Deliberately unconnected to any
  // clue chain — the point is that not everything you notice has to matter
  // to the mystery for noticing to be worth doing.
  {
    id: 'tgt_park_marker',
    name: 'Weathered Dedication Stone',
    category: 'relic',
    material: 'stone',
    materialName: 'Worn granite',
    rarity: 'uncommon',
    era: 'Unknown',
    depth: [0, 0],
    size: 0.4,
    value: 3,
    significance: 'minor',
    fragility: 0,
    excavationDifficulty: 0,
    description:
      'Set flush into the ground near an old path, low enough that most people walk straight over it. Whatever it once commemorated has worn past reading.',
    discoveryText: 'A dedication stone, face down in the grass more often than not.',
    silhouette: 'carving',
  },
  {
    id: 'tgt_railway_plate',
    name: 'Signal Plate',
    category: 'relic',
    material: 'stone',
    materialName: 'Enamelled steel',
    rarity: 'uncommon',
    era: 'Unknown',
    depth: [0, 0],
    size: 0.4,
    value: 3,
    significance: 'minor',
    fragility: 0,
    excavationDifficulty: 0,
    description:
      'Bolted to a post that has otherwise rotted away, the plate outlasted whatever it was warning about. The paint is gone; the shape of the letters almost isn’t.',
    discoveryText: 'A signal plate, still bolted to a post with nothing left to hold up.',
    silhouette: 'carving',
  },
  {
    id: 'tgt_mine_warning',
    name: 'Chalked Warning Mark',
    category: 'relic',
    material: 'stone',
    materialName: 'Chalk on timber',
    rarity: 'uncommon',
    era: 'Unknown',
    depth: [0, 0],
    size: 0.4,
    value: 3,
    significance: 'minor',
    fragility: 0,
    excavationDifficulty: 0,
    description:
      'A mark chalked onto a tunnel support, half worn away by damp air. Somebody wanted the next person through here to know something. It no longer says what.',
    discoveryText: 'A chalk mark on old timber, mostly gone but clearly deliberate.',
    silhouette: 'carving',
  },

  // ── Home: found by looking, not digging — the trail's first and last stop.
  {
    id: 'tgt_home_note',
    name: 'Torn Field Note',
    category: 'personal',
    material: 'organic',
    materialName: 'Paper',
    rarity: 'uncommon',
    era: 'Recent',
    depth: [0, 0],
    size: 0.3,
    value: 0,
    significance: 'notable',
    fragility: 0.4,
    excavationDifficulty: 0,
    description:
      "Half a page, torn clean across the middle, in his handwriting: three ordinary-looking sites around town, and one line underlined twice — \"something underneath all three.\" He never mentioned any of this over dinner.",
    discoveryText: "A page from his own notebook — the half he didn't take with him.",
    examineText: 'The tear is fresh. Whatever was on the other half, he wanted it separate from this half.',
    silhouette: 'fragment',
  },
  {
    id: 'tgt_home_mystery_artifact',
    name: 'Something Underneath',
    category: 'artifact',
    material: 'unknown',
    materialName: 'Unknown',
    rarity: 'legendary',
    era: 'Unknown',
    depth: [0, 0],
    size: 0.4,
    value: 250,
    significance: 'unknown',
    fragility: 0.6,
    excavationDifficulty: 0,
    unidentifiedName: 'Object, Origin Unclear',
    description:
      'Small, heavy for its size, marked with the same three-pointed sun you have now seen carved into stone hundreds of miles from this yard. Nobody buried this here. It was just already in your mouth.',
    discoveryText: 'Somewhere between the ruins and home, this ended up with you. You do not remember picking it up. You are a cat; you rarely do.',
    examineText: "He will ask where you got this. You will not have an answer he can use.",
    silhouette: 'oddity',
  },

  // ── The Silent Court's inner vault: reached through a gap only CK fits
  // through. One find continues the footprints/crate thread left dangling
  // by the main court; the other is the vault's own reward.
  {
    id: 'tgt_court_intruder_tin',
    name: 'Sealed Tin, Modern Make',
    category: 'personal',
    material: 'nonFerrous',
    materialName: 'Tinplate',
    rarity: 'uncommon',
    era: 'Recent',
    depth: [8, 14],
    size: 0.35,
    value: 3,
    significance: 'notable',
    fragility: 0.15,
    excavationDifficulty: 0.2,
    unidentifiedName: 'Buried Tin, Recent',
    description:
      'A watertight tin, buried on purpose rather than lost — the lid seats too well for an accident. Inside, gone soft with damp: a folded page of survey notes in a hand that is not his, and not old.',
    discoveryText: "Someone hid this. Recently. In a court nobody else has any reason to be in.",
    examineText:
      "The boot prints out front, the crate by the entrance, and now this. Whoever left them was not passing through — they were working, and hiding what they found the same way anyone does.",
    clueId: 'clue_court_intruder',
    silhouette: 'tin',
  },
  {
    id: 'tgt_court_shard_b',
    name: 'Second Shard',
    category: 'artifact',
    material: 'stone',
    materialName: 'Glazed earthenware',
    rarity: 'uncommon',
    era: 'Unknown',
    depth: [0, 0],
    size: 0.35,
    value: 5,
    significance: 'minor',
    fragility: 0.3,
    excavationDifficulty: 0,
    description:
      'Set into a recess behind the weighted plate — the same glaze, the same curve as the shard from the court outside. Whoever built this court hid it from anyone tall enough to walk in the front way, which is most people, and exactly none of the cats.',
    discoveryText: 'Behind the plate, exactly where the weight said something would be — and it matches.',
    silhouette: 'potteryShard',
    pieceOf: 'tgt_court_vessel',
  },
  {
    id: 'tgt_court_vessel',
    name: 'The Reassembled Vessel',
    category: 'artifact',
    material: 'stone',
    materialName: 'Glazed earthenware',
    rarity: 'veryRare',
    era: 'Unknown',
    depth: [0, 0],
    size: 0.5,
    value: 300,
    significance: 'notable',
    fragility: 0.5,
    excavationDifficulty: 0,
    description:
      'Two shards, glued by nothing but the shape of the break, make a single small vessel — coiled serpents pressed into the clay before it was fired, the same pair from the walls outside. The break itself is wrong for an accident: too clean, too deliberate, and recent. Somebody split this in half on purpose, and put the halves as far apart as this small court allows.',
    discoveryText: 'The two pieces settle together like they were always the same object. Which they were, until somebody decided they shouldn\'t be.',
    examineText:
      "The fresh edge is a hand tool's cut, not a fall. Whoever did this knew exactly what this vessel was — and would rather it stayed in pieces than let the wrong person hold it whole. That is not how you treat rubbish. That is how you hide something from someone you don't trust.",
    silhouette: 'idol',
    unidentifiedName: 'Reassembled Vessel',
    assemblyOf: ['tgt_court_shard', 'tgt_court_shard_b'],
    clueId: 'clue_court_vessel',
    authored: true,
  },
];

const TARGET_INDEX = new Map(TARGETS.map((t) => [t.id, t]));

export function getTarget(id: string): TargetDef | undefined {
  return TARGET_INDEX.get(id);
}

/** Used by the journal so an unknown id in an old save degrades gracefully. */
export function getTargetOrPlaceholder(id: string): TargetDef {
  return (
    TARGET_INDEX.get(id) ?? {
      id,
      name: 'Unidentified Find',
      category: 'junk',
      material: 'unknown',
      materialName: 'Unknown',
      rarity: 'common',
      depth: [0, 0],
      size: 0.4,
      value: 0,
      significance: 'unknown',
      fragility: 0,
      excavationDifficulty: 0.3,
      description: 'Your notes on this find are incomplete.',
      discoveryText: 'Your notes on this find are incomplete.',
      silhouette: 'oddity',
    }
  );
}
